### ISSUE TITLE
How to obtain the dataset?

### ISSUE THREAD

**Issue by zxc123cc** [umass-ml4ed/distractor-ranking-BEA#1]
Dear Author,

I would like to know how I can obtain the dataset. I have downloaded the dataset from eedi, but I'm not sure how to process it.

**Comment by overbridge-wanyong** [comment]
https://github.com/umass-ml4ed/prompt_distractor_generation_NAACL/issues/2#issuecomment-2384052135

**Comment by JasonCZH4** [comment]
> Dear Author,
> 
> I would like to know how I can obtain the dataset. I have downloaded the dataset from eedi, but I'm not sure how to process it.

Hi,  may I ask how can I get the dataset? Is there a direct downloading link? Thanks!
